# Name of your workflow
name: Deploy to EC2 on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd hngxiii-stage2-countries-api
            git pull
            pnpm install
            pnpm build
            npx typeorm-ts-node-commonjs migration:run -d dist/typeorm-cli.config.js
            # restart pm2 process
            pm2 restart hngxiii-countries-api
